### ISSUE TITLE
Cannot install version 0.2

### ISSUE THREAD

**Issue by tierriminator** [harlanhaskins/LLVMSwift#107]
Swift PM failes to install LLVMSwift 0.2 with the following dependency telling error: unsatisfiable:
`.Package(url: "https://github.com/trill-lang/LLVMSwift", majorVersion: 0, minor: 2)`
Using:
Swift 3
Xcode 8.3.3
LLVM 5.0.0

When using
`.Package(url: "https://github.com/trill-lang/LLVMSwift", majorVersion: 0)`
Swift PM fetches LLVMSwift 0.1.11

**Comment by harlanhaskins** [comment]
@codafi Is this a Swift 4 issue? You might need to update to Xcode 9.

**Comment by CodaFi** [comment]
When we updated to LLVM 5.0, we also updated to the Swift 3.2/4.0 toolchain.  You must build with Xcode 9.

**Comment by tierriminator** [comment]
Ok, it seems to work with Swift 4, therefore I close this issue, as there is now a note in the release of v0.2 (if I'm correct it wasn't there before).
Thanks
