### ISSUE TITLE
LLVMGenericValueRef needs to be wrapped

### ISSUE THREAD

**Issue by kasei** [harlanhaskins/LLVMSwift#117]
In trying to use `JIT.runFunction` I ran into trouble in trying to figure out how to use the `IRValue` return values. There doesn't seem to be any exposed API for unwrapping these values to access the native value of the return type.

@harlanhaskins [suggested on Twitter](https://twitter.com/harlanhaskins/status/951961613371871233) that a swift API is needed that wraps `LLVMGenericValueRef` functionality.

**Comment by CodaFi** [comment]
Some bad news: I'll be removing `JIT.runFunction`.  `LLVMRunFunction` calls `MCJIT::runFunction` which is deprecated in favor of the new `ORCJIT` `ExecutionEngine`.  As such, it is only capable of running main and main-like prototypes and not arbitrary functions.  #102 provides initial ORCJIT bindings, but we are still in talks with its maintainers about a more robust C API.  In the meantime you can always follow the example in the README and cast to a function pointer and call.

I will still be closing this ticket as of #118.

**Comment by kasei** [comment]
Unfortunately the example in the README isn't nearly as flexible as something like runFunction because, AFAICT, the types have to be known statically as opposed to the polymorphism allowed by wrapping function arguments as `IRValue`s. Does that sound right, or have I missed anything in the API that would allow dynamic handling of argument/return types?

**Comment by CodaFi** [comment]
> Unfortunately the example in the README isn't nearly as flexible as something like runFunction because, AFAICT, the types have to be known statically as opposed to the polymorphism allowed by wrapping function arguments as IRValues.

The `runFunction` API, while tantalizing, never did what you think it does.  I'm surprised it got wrapped at all, it was really just the implementation part of `runFunctionAsMain`.

**Comment by kasei** [comment]
Fair enough. Perhaps I misunderstood what it does. Is there any way to do what I'm after, then (JIT compiling functions whose type is unknown at swift compile time, and dynamically constructing an invocation that allows accessing the return value)?

**Comment by CodaFi** [comment]
What do you mean by "unknown types"?  LLVM is a statically typed intermediary language.  The best you could do to try and achieve "polymorphism" would be to pass around variadic pointers to tagged unions.

**Comment by CodaFi** [comment]
(Essentially: What are you trying to do here?)

**Comment by kasei** [comment]
I'm compiling typed expressions derived from database queries. The exact type of the expressions isn't known at the point my code is compiled – it comes as input at runtime. `runFunction` *seemed* to be a good fit in that I could dynamically construct an array of `IRValue`s to be used as function arguments, but as you've indicated, it seems I misunderstood what that function does.

**Comment by harlanhaskins** [comment]
Which is understandable, because it was completely undocumented in both the C API sand LLVMSwift.
