### ISSUE TITLE
Setup (cllvm.pc)

### ISSUE THREAD

**Issue by therealbnut** [harlanhaskins/LLVMSwift#133]
I had to run this to get it to work, it's non-obvious that you've got to do this from the README.md, is this what I'm meant to have done?
```
chmod +x .build/checkouts/LLVMSwift.git-*/utils/make-pkgconfig.swift
.build/checkouts/LLVMSwift.git-*/utils/make-pkgconfig.swift
```

**Comment by CodaFi** [comment]
The README says you should be able to use the Swift interpreter.  Did that really require exec permissions?

> $ swift ./utils/make-pkgconfig.swift

**Comment by therealbnut** [comment]
Ah, my mistake was doing this when it was already a dependency. The README on a second read suggests it’s on a clone of LLVMSwift.

It might be interesting to make `utils` a target of the package... I’ll play around with that and get back to you.

**Comment by CodaFi** [comment]
Alright then. In the mean time I’ll close this out.
