### ISSUE TITLE
Integer Type Aliases

### ISSUE THREAD

**Issue by daviejaneway** [harlanhaskins/LLVMSwift#137]
Hi there,

I've been working with LLVMSwift for a while now for my language backend. Love it, really good job! One thing I'm struggling with is how to create an alias for llvm's integer types.

Is there a way that I can emit something like "%Int32 = type i32"?

Many thanks

**Comment by CodaFi** [comment]
So glad to hear you're having a good time with LLVMSwift.

Can you elaborate a bit on why you need the type alias to be emitted at all?  It's certainly a legal IR declaration but I can't think of a reason you would want a typedef of a builtin type.

**Comment by daviejaneway** [comment]
Thanks for getting back to me.

My compiler works as a set of independent passes that don't know about each other. The way typenames work in my language makes it tricky to work with the llvm types. Ideally, I want to "trick" the compiler into thinking the types from llvm (or any other backend target) are just normal types in my language.

The way I wanted to do it was as a rewrite rule (macro) that just spits out a typealias into the llvm module.

I can work around it by relaxing things in the type system etc but would have been an elegant solution.

**Comment by CodaFi** [comment]
Sounds like you want to define an abstract base class and a subclass with LLVM-specific operations.  Making that evident in the IR level seems like an unnecessary inversion of responsibility for a generic backend.

In Silt, for example, we have the benefit of an intermediate language that roughly figures out data layouts.  The backend then interprets these results as LLVM types and instructions as needed.

**Comment by daviejaneway** [comment]
Many thanks for your suggestions there, I will have a rethink about how I'm doing things. An intermediate representation between Orbit (my language) and the various backends might actually be the best way to go.

Thanks again for your help and for the project. I hope I can find a way to contribute back.
