### ISSUE TITLE
Seg fault upon accessing `Module.name`

### ISSUE THREAD

**Issue by matthewseaman** [harlanhaskins/LLVMSwift#170]
Attempting to access `module.name` on a `Module` causes a EXC BAD ACCESS.

**Comment by matthewseaman** [comment]
This just seems to be because of `nil` being passed in as the `UnsafeMutablePointer` `count` parameter of `LLVMGetModuleIdentifier`. I can tackle this one.

**Comment by matthewseaman** [comment]
@CodaFi I have a fix on a local branch. I can create a PR if you add me as a contributer.

**Comment by Azoy** [comment]
You shouldn't need any special permissions to submit a PR, so you should be good to go.
