### ISSUE TITLE
Does not compile under LLVM 9

### ISSUE THREAD

**Issue by ThatsJustCheesy** [harlanhaskins/LLVMSwift#215]
LLVMSwift won't compile under LLVM 9. Some of LLVMSwift's LLVM-C API extensions appear to have been upstreamed, causing errors such as the following:

```
llvmshims/src/shim.cpp:43:5: redefinition of enumerator 'LLVMBinaryTypeArchive'
    LLVMBinaryTypeArchive,
    ^
llvmshims/src/shim.cpp:44:5: redefinition of enumerator 'LLVMBinaryTypeMachOUniversalBinary'
    LLVMBinaryTypeMachOUniversalBinary,
  ^
# etc.
```

I'm not sure what the protocol is for adopting upstream versions of these API. i.e., do older LLVM versions still have to be supported? If so, should that be done with version macros, or otherwise?

(btw, this package has been excellent to me, thank you for maintaining it!)

**Comment by dduan** [comment]
I'll have patch for this.

**Comment by ThatsJustCheesy** [comment]
If it would help anyone, my fork has a port to LLVM 9 on the `llvm-9` branch. It's hacky (I deleted stuff that appeared to have been upstreamed into LLVM proper until it compiled) but I haven't had any issues for over a month of using it. See https://github.com/ThatsJustCheesy/LLVMSwift/tree/llvm-9

dduan seemed to be having issues with the CI system, so this is just a temporary workaround.
