### ISSUE TITLE
LLVMSwift does not compile if the system LLVM version is the default (11)

### ISSUE THREAD

**Issue by twof** [harlanhaskins/LLVMSwift#218]
`brew install llvm` as recommended in the installation section of the readme installs LLVM 11 which causes LLVMSwift to fail to compile. This problem can be resolved by instead running `brew install llvm@9` to install LLVM 9 which appears to be the most recent version of LLVM supported by LLVMSwift. 

I don't know what's gained by using LLVM 11 over 9, but until 11 can be supported, I'll submit a PR to fix the README.

**Comment by matthewseaman** [comment]
Is this issue ready to be closed?

**Comment by twof** [comment]
Yep!
