### ISSUE TITLE
LLVMSwift does not wrap LLVM{Get|Set}SourceFileName

### ISSUE THREAD

**Issue by ColMcp** [harlanhaskins/LLVMSwift#223]
In my little example compiler I want to record the source file name that was processed to create an llvm module. The C API of llvm does seem to allow this but as far as I can see LLVMSwift does not wrap it. I added the following code to Sources/LLVM/Module.swift immediately before the line starting `public var inlineAssembly: String {`: 

```
/// The source filename of this module.
public var sourceFileName: String {
   get {
     var count = 0
     guard let fn = LLVMGetSourceFileName(llvm, &count) else { return "" }
     return String(cString: fn)
   }
   set {
     LLVMSetSourceFileName(llvm, newValue, newValue.utf8.count)
   }
}

```
Setting a module's sourceFIleName variable results in a line like the following being added to the .ll file:
`source_filename = "/Users/.../Local/Swift/Tmp/tigon/minimal.tig"`

**Comment by matthewseaman** [comment]
Are you up for throwing this into a PR or would you rather someone else do it?

**Comment by ColMcp** [comment]
I'd be happy for you or anyone else to create a pull request. My oldster-type brain never really moved on from running manual `diff` and `patch` commands.

**Comment by matthewseaman** [comment]
This should pop up in 0.8 whenever that is tagged.
