### ISSUE TITLE
'llvm-c/LinkTimeOptimizer.h' file not found

### ISSUE THREAD

**Issue by franktinsley** [harlanhaskins/LLVMSwift#235]
Followed installation instructions but continue hitting the error message `'llvm-c/LinkTimeOptimizer.h' file not found`. Any clues?

**Comment by matthewseaman** [comment]
1. Are you on macOS or Linux?
2. What is the output of `llvm-dis --version` in Terminal?
2. Did you install llvm via `brew` or something else?
3. What's the output of `cat /usr/local/lib/pkgconfig/cllvm.pc`? (`/usr/local` may need replaced with the output of `brew --prefix`.)
4. If you're trying to build in Xcode, ensure you're trying to build for a Mac target.

**Comment by franktinsley** [comment]
1. macOS
2. zsh: command not found: llvm-dis
3. brew
4. `Name: cllvm
Description: The llvm library
Version: 12.0.0
Libs: -L/usr/local/Cellar/llvm/12.0.0_1/lib -lLLVM-12 -lc++
Requires.private:
Cflags: -I/usr/local/Cellar/llvm/12.0.0_1/include%`

**Comment by matthewseaman** [comment]
Note: LLVMSwift is currently targeted at LLVM 11 and has not been tested with LLVM 12.

With that in mind, it looks like LLVM might not be in your path. Make sure the path to the LLVM libraries is somewhere in your path. (e.g. add `export PATH="/usr/local/opt/llvm@12/bin:PATH"` to `~/.zshrc`; this path could be slightly different depending on the install, for example by using a different `@V` version number or removing the `@V` altogether)

After doing that (and restarting your Terminal session), you may need to rerun `swift utils/make-pkgconfig.swift`

**Comment by franktinsley** [comment]
Ah yeah that was the issue, the path and the wrong LLVM version. Switching to 11 and having that in my path got it building. Thanks so much!
