### ISSUE TITLE
Storing Strings

### ISSUE THREAD

**Issue by calebkleveter** [harlanhaskins/LLVMSwift#92]
I am trying to create the code generation process for a compiler. I am able to do almost everything I need except to create a `StringType`.

I can create strings this way:

```swift
builder.buildGlobalStringPtr("Hello, world!\n", name: "hello-world")
```

But that creates a global string. I want to be able to set the a function parameters type to string like I can for an Int or Float. Am I just trying to go about this the wrong way?

Here is an example of what I would like to do:

```swift
FunctionType(argTypes: [StringType], returnType: FloatType.float)
```

**Comment by segiddins** [comment]
I think a string is just going to be a pointer to the global [i8 x length], LLVM doesn't really have a notion of a string type

**Comment by segiddins** [comment]
Feel free to ask any further questions in our [slack](https://llvmswift-slack.herokuapp.com)
